version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  python_example:
    run: python:latest analysis/example.py
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/python.feather*

  stata_example:
    run: stata-mp:latest analysis/example.do
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/stata.dta.gz

  r_example:
    run: r:latest analysis/example.r
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/r.feather*
